"""empty message

Revision ID: 0dd78df7fd5f
Revises: a5ec090ac8f7
Create Date: 2020-06-01 16:10:56.390154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd78df7fd5f'
down_revision = 'a5ec090ac8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('score', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
