"""empty message

Revision ID: 5d7fd0e5692b
Revises: 0dd78df7fd5f
Create Date: 2020-06-01 16:15:28.240982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7fd0e5692b'
down_revision = '0dd78df7fd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('score', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
