"""empty message

Revision ID: 85a326d44a73
Revises: 5d7fd0e5692b
Create Date: 2020-06-01 16:15:57.902592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a326d44a73'
down_revision = '5d7fd0e5692b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('score', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
