"""empty message

Revision ID: a5ec090ac8f7
Revises: 1eb36c8fef16
Create Date: 2020-06-01 16:10:19.189151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ec090ac8f7'
down_revision = '1eb36c8fef16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('score_d', sa.Integer(), nullable=True))
    op.add_column('paper', sa.Column('score_n', sa.Integer(), nullable=True))
    op.drop_column('paper', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('score', sa.FLOAT(), nullable=True))
    op.drop_column('paper', 'score_n')
    op.drop_column('paper', 'score_d')
    # ### end Alembic commands ###
