"""empty message

Revision ID: b57df45581b0
Revises: a13591ec6ce4
Create Date: 2020-05-29 10:40:54.726567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57df45581b0'
down_revision = 'a13591ec6ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('authors', sa.String(length=256), nullable=True))
    op.add_column('paper', sa.Column('comment', sa.String(length=256), nullable=True))
    op.add_column('paper', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('paper', sa.Column('voted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'voted')
    op.drop_column('paper', 'score')
    op.drop_column('paper', 'comment')
    op.drop_column('paper', 'authors')
    # ### end Alembic commands ###
